spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=stripe-provider-service
stripe.api.key=sk_test_51SxijQEY9xjEC1fgg1B1iFrdeEqR1SVOGhdyMiDUOJVlpsn6ATP1lPt514l3QmHnaec6ROGyzs3ZoIfXOVTbtK4j00GBY7DYj5
stripe.create.session.url=https://api.stripe.com/v1/checkout/sessions